#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items"

FONT="SF Pro"
NERDFONT="SFMono Nerd Font"

HELPER=peter.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

##### Bar Appearance #####
#Configuring the general appearance of the bar, these are only some of the
#options available.For all options see:
#https: // felixkratz.github.io/SketchyBar/config/bar
#If you are looking for other colors, see the color picker:
#https: // felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  height=32
  blur_radius=50
  shadow=on
  position=top
  sticky=on
  corner_radius=9
  y_offset=10
  margin=12
  padding_left=10
  padding_right=10
  # color=$BACKGROUND_2
  color=0x45000000
)

sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
#We now change some default values that are applied to all further items
#For a full list of all available item properties see:
#https: // felixkratz.github.io/SketchyBar/config/items


default=(
  updates=when_shown
  drawing=on
  icon.font="$NERDFONT:Bold:14.0"
  icon.color=0xffffffff
  label.font="$FONT:Bold:14.0"
  label.color=0xffffffff
  label.padding_left=4
  label.padding_right=4
  icon.padding_left=4
  icon.padding_right=4
  background.padding_right=3
  background.padding_left=3
  background.height=26
  background.corner_radius=9
  popup.background.corner_radius=11
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.background.shadow.drawing=on
)

sketchybar --default "${default[@]}"
##### Adding Mission Control Space Indicators #####
#Now we add some mission control spaces:
#https: // felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
#to indicate active and available mission control spaces

source "$ITEM_DIR/apple.sh"


SPACE_ICONS=("" "" "" "󰻏" "ﱘ" "" "ﱘ" "󱩛")

for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  sketchybar --add space space.$sid left                                 \
             --set space.$sid associated_space=$sid                      \
                              icon=${SPACE_ICONS[i]}                     \
                              icon.padding_left=8                        \
                              icon.padding_right=8                       \
                              icon.font="$NERDFONT:White:16.0"               \
                              background.padding_left=5                  \
                              background.padding_right=5                 \
                              background.color=0x44ffffff                \
                              background.corner_radius=5                 \
                              background.height=22                       \
                              background.drawing=off                     \
                              label.drawing=off                          \
                              script="$PLUGIN_DIR/space.sh"              \
                              click_script="yabai -m space --focus $sid"

done

sketchybar --add bracket space_bracket space.1 space.2 space.3 space.4 space.5  \
           --set space_bracket                                                  \
                 background.color=BACKGROUND_1                                  \
                 background.corner_radius=4                                     \
                 background.height=26
# background.color=0x10ffffff


##### Adding Left Items #####
#We add some regular items to the left side of the bar
#only the properties deviating from the current defaults need to be set

sketchybar --add item space_separator left                         \
           --set space_separator icon=                            \
                                 background.padding_left=15        \
                                 background.padding_right=15       \
                                 label.drawing=off                 \


source "$ITEM_DIR/front_app.sh"

#-- add item front_app left #-- set front_app script =                         \
    # "$PLUGIN_DIR/front_app.sh" #icon.drawing =                                 \
        # off #-- subscribe front_app front_app_switched

##### Adding Right Items #####
#In the same way as the left items we can add items to the right side.
#Additional position(e.g.center) are available, see:
#https: // felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

sketchybar --add item clock right                        \
           --set clock   update_freq=10                  \
                         script="$PLUGIN_DIR/clock.sh"   \
                                                         \
          

source "$ITEM_DIR/battery.sh"
#source "$ITEM_DIR/calendar.sh"

#source "$ITEM_DIR/volume.sh"

source "$ITEM_DIR/vpn.sh"

source "$ITEM_DIR/bluetooth.sh"

source "$ITEM_DIR/volume.sh"

# source "$ITEM_DIR/stats.sh"

source "$ITEM_DIR/cpu.sh"

source "$ITEM_DIR/pomodoro.sh"

sketchybar --add item mirror right \
           --set mirror icon= \
                        padding_right=5  \
                        icon.color=0xffffffff \
                        icon.font="$NERDFONT:White:16" \
                        click_script='open -a "Hand Mirror"'

#sketchybar-- add alias "Flow,Item-0" right
#source "$ITEM_DIR/flow.sh"
##### Adding Center Items #####

source "$ITEM_DIR/music.sh"

#sketchybar-- add alias "Menu Bar Ticker,Item-0" center
#sketchybar-- set "Menu Bar Ticker,Item-0" associated_display = 1
#sketchybar-- set "Menu Bar Ticker,Item-0" click_script =                      \
    # "osascript -e 'tell application \"Music\" to launch'; osascript -e 'tell application \"Music\" to playpause'"


##### Finalizing Setup #####
#The below command is only needed at the end of the initial configuration and
#should never be run in an item script.

sketchybar --update

echo "sketchybar configuration loaded.."
